### ISSUE TITLE
Ogg Vorbis playback not working due to typo/oversight

### ISSUE THREAD

**Issue by thijsputman** [home-assistant-libs/aioslimproto#239]
There appears to be a typo/oversight in `client.py` which is causing Ogg Vorbis playback to not work:

https://github.com/home-assistant-libs/aioslimproto/blob/a1da24578456ff9f7a8fc3f69c166cde67632b84/aioslimproto/client.py#L184

The format-byte for Ogg should be `o` (lowercase "Oh") not `0` (zero) – see also the Wiki-page referenced in the comment above the definition itself: https://wiki.slimdevices.com/index.php/SlimProto_TCP_protocol.html#Command:_.22strm.22

**Comment by marcelveldt** [comment]
Thanks!
And sorry for the late response btw
