### ISSUE TITLE
Add multiroom support 

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [home-assistant-libs/aioslimproto#61]
This is the last step I need to switch completely from lms to music-assistant and this slimproto integration here.

I really need a chance to create group of my [squeezelite-esp32](https://github.com/sle118/squeezelite-esp32) clients.
Have no plan how difficult this is but this is really my last puzzle. :)

I am running [squeezelite-esp32](https://github.com/sle118/squeezelite-esp32) on five ESP32-A1S modules. These modules a ready usable for non technical dudes who are not able to solder little boards. :) And easy flashable with usb, a chrome browser and this:
https://raspiaudio.github.io/
(You need to choose I2S and setup then some parameters, thats all)

I think these modules are ideal to enable anyone to build a multiroom system. Unfortunately, I think that lms is too old-fashioned for some users, so slimproto together with homeassistant could be an ideal solution.

**Comment by marcelveldt** [comment]
multi room sync is in the works as we speak. It takes a bit longer than I hoped but the results are going to be great.
I replay hope to release the first beta version within 1...2 weeks

**Comment by sorryusernameisalreadytaken** [comment]
This sounds awesome! I am already looking forward to trying out the first beta versions. I have the releases here on the watchlist.

Thank you for this great project <3

**Comment by sorryusernameisalreadytaken** [comment]
> multi room sync is in the works as we speak. It takes a bit longer than I hoped but the results are going to be great. I replay hope to release the first beta version within 1...2 weeks

I don't want to be intrusive. I would just be interested to know if there has been any progress here.

**Comment by marcelveldt** [comment]
Yes, but multiroom.grouping support will be implemented in Music Assistant and not in the slim-proto integration.

**Comment by sorryusernameisalreadytaken** [comment]
Is there any beta or similar? I really wanna test it.

**Comment by marcelveldt** [comment]
No, keep an eye on the Music Assistant discord and beta versions. 
I think somewhere like halfway November

**Comment by sorryusernameisalreadytaken** [comment]
I see you closed this issue on may 29. Does that mean that music-assistant is now able to handle my [squeezelite-esp32](https://github.com/sle118/squeezelite-esp32) clients with multi-room and in sync?

**Comment by marcelveldt** [comment]
Correct
